language: ruby
rvm:
  - 2.2.3

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "bitfurry"
      - git config --local user.email "bitfurry@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: TZNvCg8S/fmh95VQxDszc3o86AD+PeYWNxdt3D617PRpWFxzCnjrCSCQykcW2IEVOV1AXkJusXUMieuYqEL+po5Yf5/Fwpn5tRNDC5ZkYUWIMNW3L5ih60UtQp9VzjnwJ8AJYzF5i2UZdiWM6APjPbqtLEU6BajOw+Kymm7neHF/CKSF5V8usKiwpu4Lir3kORVLvBf173PWQ8LOGNeMMGw2JL0NGl5Y1M+TCFJhY9hRUJTLANL44w5XpwELL4njLM13nORk5sVWVXbNxK7DEvRpKSQNjCHKVjgAKq2nKmHH6RvV69rRxi+5qsooQXqbmeNl1bQXrrxwx6LlYZn54aiJbkAiuMwL73rJVFc/DT1QgkDrlH1NF1lnUdepOWfW+rreJVGXkovkrdfKvA0CUk1MMhs40GoDPCrt+sHrXfoJcg9ndXcNaVEh6fhakaDiH08l2YDfJxB1uMGsmDD5PfNLW9xgtLG09foTvwOVq+X0cNSYFnNxZ25BSVDA8Pz1qTaEE3t9KvfxjwKM07IbrnPwBoxGFZAWk0XL99hmoI7ekPDz3KUOvsIU2H9IP5kxaF/K5Wv1xwt7s/Tzns54HExB9JmrLfZjsYxiOfTwLBUSOCDQN6mlNsrOVz2331iTwThme0ZmVxM9umz6xHY91nqTb5ZGepgx6zfSR3NrN7A=
  skip_cleanup: true

addons:
  artifacts: true
