language: ruby
rvm:
<<<<<<< HEAD
  - 2.3.0

=======
- 2.2.3
>>>>>>> some try
before_deploy:
- git config --local user.name "bitfurry"
- git config --local user.email "bitfurry@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: rrI195WibpGwf/T5MTzrDlNeDN315wUefOVXBDj7+70dG7z0ds30ZRJi5PZ1lZfa5kMM5Lg6uvU3af5DcLMv568kwWEQ87rhkhJ9O3wH3Tf1KAyc2aaYv4MsHVZ0vLRnbvlxZq/5nlAZxNEwuScm/OzwGytjzqxKIfVUZVlPY72H3Bx126oRXgS71FRM1Nrqqa/5gFM4zKJEnWlmOxddRD2XTslJTMhw7294Gk3SqB115NdN6dIBSM2fbGjScshRNf4EmTSjhFW9fsXaJiTRA+UJSxPZytpe+RcWNPVTcuSKqEazkqXWWkMJGqXiCzwpRaOvBELee9nlTRDbQVVBP9X08TVSCh6Oav3qYu3WlIMKMt3SBqnJ4Iuq+wTRvUMFWsUsENaBfQOsio/Snsll/wQ1e5+VgvFo9Gdf72oHPXy4fP7Si/qeO1aTBJzxFwz7WOFjkyFTVuoWH9ecRs6qQb6jpJrOQp6xLxZOuf5gY8c8ZFyQVKkRzA+93L/LYF3UGnRwWNFdbfIEQA7p2V2CdQRUcdcsCd8ZFmMJWqO0ITDL1+2RqRhTvfpsFwSRSQtYbTa4Yo6P4JAUdRxks/NFOZKfw3J7mc8X1uDD7BEje1dUqDHSkGC/cTH/PGDFg0kDDOXVGlU5jeHCBMVWC1qixw7+4eazt/xcewZ32nRh2iQ=
  file: hello_world.rb
  on:
    repo: bitfurry/den_setup
addons:
  artifacts: true
>>>>>>> some try
